services:
  app:
    build: .
    container_name: amazon_purchases
    restart: always
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    # volumes:
    #   - ./uploads:/app/uploads # optional if you want to save uploads
