version: "3.8"

services:
  app:
    build: .
    container_name: amazon_purchases
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development

  redis:
    image: "redis:alpine"
    container_name: redis

  celery_worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    user: appuser
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=false
    depends_on:
      - redis
