services:
  app:
    build: .
    container_name: amazon_purchases
    ports:
      - "5001:5000"
    volumes:
      - ./uploads:/app/uploads # optional if you want to save uploads
      - ./data:/app/data # Add this line for database persistence
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    container_name: redis

  celery_worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
